//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eindopdracht
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {

        }
        public Inventory(int id1, int id2)
        {
            NinjaID = id2;
            EquipmentID = id1;
        }

        public int Id { get; set; }
        public int NinjaID { get; set; }
        public int EquipmentID { get; set; }
    }
}
