//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eindopdracht
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ninja
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Currency { get; set; }
        public int InventoryID { get; set; }
    }
}
