CREATE TABLE [dbo].[Inventory](
	[NinjaID] [int] NOT NULL,
	[EquipmentID] [int] NOT NULL,
-- CONSTRAINT [PK_Inventory] PRIMARY KEY CLUSTERED 
--(
--	[Id] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--) ON [PRIMARY]
PRIMARY KEY ([NinjaID], [EquipmentID]),
CONSTRAINT [fk_ninja_equipment] FOREIGN KEY(NinjaID) REFERENCES Ninja(Id),
CONSTRAINT [fk_equipment_ninja] FOREIGN KEY(EquipmentID) REFERENCES Equipment(Id)
)